# Generated by Django 3.2.4 on 2021-06-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
