# Generated by Django 3.2.4 on 2021-06-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210629_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Responses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.response'),
        ),
    ]
